### ISSUE TITLE
Add button to open the drape algorithm

### ISSUE THREAD

**Issue by ghtmtt** [faunalia/trackprofile2web#4]
So that the user can handle all the steps in one dialog.

**Comment by ghtmtt** [comment]
I'm not so sure about this anymore. Opening the algorithm windows means that the user already has a DEM file loaded somewhere, else it is totally useless. 

IMHO the behavior of the algorithm is simple (is the data are correct) and should stay as simple as we can. What is your opinion @Raruto?

**Comment by Raruto** [comment]
in general, I think that all processing algorithms are aimed at a mid-level qgis user (in particular for access through UI quite difficult to find, if you don't know exactly what you need..)
It's true that the algorithm itself is nothing too much hard, but I believe that in the future we will have to find a better way to approach even inexperienced users (eg. like an interactive step by step guide that illustrates the concept of "draping a dem", which is not really "suitable" for everyone...)

**Comment by ghtmtt** [comment]
@Raruto I think 0dc559c solves this issue. Basically if the layer has not Z values, the same messageBar of before appears with the additional button to open the drape algorithm:

![immagine](https://user-images.githubusercontent.com/2884884/59097010-b9c07c00-891c-11e9-9a39-5918ed90911b.png)

Reopen if necessary.
